### ISSUE TITLE
Javascript output use BigDecimal unknown

### ISSUE THREAD

**Issue by Dexus** [jenner/LstGen#10]
Hi, javascript output use BigDecimal but not very much browsers support it. Is there any polifill?

**Comment by jenner** [comment]
It's nearly impossible to suggest a default BigDecimal implementation, the JS package landscape is huge, see e.g. https://dev.to/fvictorio/a-comparison-of-bignumber-libraries-in-javascript-2gc5
I guess my initial idea of just using "BigDecimal" was to let the user choose which package to use and provide a matching wrapper much like the one I added for python.

**Comment by Dexus** [comment]
ok, that will make sense for me now. thank you.
