### ISSUE TITLE
Naming of PAP versions

### ISSUE THREAD

**Issue by knipknap** [jenner/LstGen#12]
First of all, Thanks a lot for putting in the work and making it available for everyone, really awesome.

It would be very helpful if the PAP versions were named in a way that they can be selected automatically. Currently they look like this:

Verfügbare PAP Versionen:
2006
2007
2008
2009
2010
2011bisNov
2011Dez
2012
2013
2014
2015bisNov
2015Dez
2016
2017
2018
2019
2020

Better would be (IMO):

2006
2007
2008
2009
2010
2011-1
2011-12
2012
2013
2014
2015-1
2015-12
2016
2017
2018
2019
2020

So each version is named according to the time where the rules come into effect. This would also be future-proof in case rules are changed mid-month in the future, e.g.

2020-11-15

**Comment by jenner** [comment]
Hi, sounds reasonable, would you like to do a PR for this?
