### ISSUE TITLE
Clarification about generator external dependency

### ISSUE THREAD

**Issue by 1605200517** [jenner/LstGen#3]
Hi, Jenner, so if I understand your tool correctly, you somehow parse BMF's APIs to create the classes?

Thank you for publishing this, by finding your tool now I have learned about BMF PAPs!

So far I have worked on my own tool but now I know how to better proceed further :-)

https://github.com/german-tax-python/lohnsteuer

**Comment by jenner** [comment]
Hi, there's no dependency to any APIs, the tool rather fetches the XMLs from [BMF](https://www.bmf-steuerrechner.de/interface/pseudocodes.xhtml) and converts the pseudo code to real code.

**Comment by 1605200517** [comment]
danke schön :-)
