### ISSUE TITLE
LstGen under Windows 11 - Error

### ISSUE THREAD

**Issue by derSESO** [jenner/LstGen#34]
Hello,
I am trying to get the whole thing to run under Windows.
Where am I making the error?

But I get the message in the Python console that “lstGen” is not known.
![Image045](https://github.com/user-attachments/assets/9ed56635-48de-44d8-b22a-b625612fc51b)

But the installation seems to have worked.
![Image044](https://github.com/user-attachments/assets/1b041188-3530-4aa2-8ba7-d1fa2dec790f)

Thanks.

PS: The PAP XML for 2025 is available.
[https://www.bmf-steuerrechner.de/javax.faces.resource/daten/xmls/Lohnsteuer2025.xml.xhtml](url)

**Comment by derSESO** [comment]
Ok, I have uninstalled again and reinstalled via CMD with admin rights.
Now the installation path is also under C:\ etc.
Then there was a problem with 'pkg_resources', which I also solved.

Now I'm stuck as follows and can't get any further:
![Image049](https://github.com/user-attachments/assets/6c5c81e5-1c99-4901-adf3-843c6f35c7f0)

**Comment by jenner** [comment]
Hi, looks like it tries to download the PAP for 2024_1 and fails for some reason, try to load https://www.bmf-steuerrechner.de/javax.faces.resource/daten/xmls/Lohnsteuer2024.xml.xhtml in a browser.

**Comment by derSESO** [comment]
Hello, is it also available in German? :)

The link works in the browser, I have the XML.
I would like to use the generation in a PHP file.
Also for 2025 then.

**Comment by jenner** [comment]
> Hello, is it also available in German? :)
Not sure what you mean

You can use the downloaded XML using -x:
-x XML_PATH, --pap-xml XML_PATH
                        Pfad zur PAP XML, falls keine PAP Version ausgewählt wurde.

**Comment by derSESO** [comment]
In Deutsch schreiben ... tuh ich mich leichter. :)
Ok, werde es mal probieren.

**Comment by derSESO** [comment]
Was soll ich sagen ... wollte eben die XML-Datei direkt in den Ordner mit der "lstgen.exe" legen.
Da lag die wohl trotz Fehler-Meldung erzeugte PHP-Datei bereits drin.
Diese scheint auf den ersten Blick ok auszusehen ... werde mich dann nachher gleich mal mit beschäftigen.

Auf jeden Fall schon mal Danke für die Rückmeldung.

Und wie im ersten Beitrag bereits erwähnt, ist die XML für 2025 ebenfalls bereits verfügbar.
Wenn nur die Anpassung/Erweiterung in der "pap.py" notwendig ist, habe ich mir die selbst eingefügt und die PHP generieren können.

**Comment by jenner** [comment]
Eine Version mit PAP 2025 habe ich eben released. Änderungen an pap.py sind allerdings nur dann nötig, wenn die XML automatisch geladen werden soll, falls die XML schon vorliegt, kann man einfach -x verwenden.

**Comment by derSESO** [comment]
Super und wie schon gesagt, danke für die schnelle Reaktion und nen guten Rutsch schon mal. :)

**Comment by jenner** [comment]
Gern geschehen und ebenfalls einen guten Rutsch!
