### ISSUE TITLE
CLI examples from readme seem to be missing arguments

### ISSUE THREAD

**Issue by hpbretz** [jenner/LstGen#7]
When I try to execute the code examples as they are shown in the Readme, they throw an error

```
% lstgen 2014 python --class-name Lohnsteuer2014 --outfile lst2014.py   
usage: lstgen [-h] [-V] [-l LANG] [-p PAP] [-x XML_PATH] [--pap-versions]
              [--outfile OUTFILE] [--class-name CLASS_NAME] [--indent INDENT]
              [--java-package-name JAVA_PACKAGE] [--php-ns PHP_NAMESPACE]
lstgen: error: unrecognized arguments: 2014 python
```

It does work with extra -p and -l arguments

```lstgen -p 2014 -l python --class-name Lohnsteuer2014 --outfile lst2014.py ```

Perhaps the readme could be ammended to include that.

**Comment by jenner** [comment]
Thanks for the hint!
