### ISSUE TITLE
possible to add Golang as output?

### ISSUE THREAD

**Issue by Dexus** [jenner/LstGen#9]
see topic: Possible to add Golang as output?

**Comment by jenner** [comment]
I'm not familiar with Go at all, however PRs are always welcome :)

**Comment by Dexus** [comment]
I'm not very familar with python :) but will try to build it.

**Comment by knipknap** [comment]
@Dexus Did you figure something out? This would be very handy for me as well

**Comment by knipknap** [comment]
The pull request works for 2014, but still has a problem with 2020. Work is in progress...

**Comment by knipknap** [comment]
Implementation is now complete

**Comment by Dexus** [comment]
> @Dexus Did you figure something out? This would be very handy for me as well

I never got around to it before because there were just too many other important things to do.

I wrote a review on your PR. Very good so far.

**Comment by jenner** [comment]
Fixed in #15

**Comment by knipknap** [comment]
Thanks for merging! 👍
